### PR TITLE
eliminate dependency on Path::Class, fixing compatibility with Dist::…

### PR DESCRIPTION
**Pull request by karenetheridge**
…Zilla 6

(see also https://rt.cpan.org/Ticket/Display.html?id=113942)

### CODE REVIEW

**Comment by DarwinAwardWinner** [comment]
How does this merge look? It passes all the tests on my computer, but I haven't tested it with dzil 6.

**Comment by DarwinAwardWinner** [comment]
Hmm, I just installed the 6.0 trial release and apparently there are some more places I need to fix.

**Comment by DarwinAwardWinner** [comment]
Oh, never mind, the warning was from an old version of the PodWeaver plugin. After upgrading that, this passes the tests with no warnings on Dzil 6. I'm going to go ahead and release it.

**Comment by karenetheridge** [comment]
thanks!

**Pull request merged**
